# Foggy London - An atmospheric Victorian colorscheme
# Inspired by Victorian London, gas lamps, fog, and cobblestone streets

[metadata]
name = "foggy_london"
display_name = "Foggy London"
author = "Claude"
version = "1.0.0"
description = "Atmospheric Victorian colorscheme inspired by foggy London streets and gas lamps"
background = "dark"

[colors]
# Base colors - Foggy foundations
bg = "#1C1B1A"
bg_alt = "#171615"
bg_highlight = "#252321"
bg_dim = "#171615"
bg_light = "#252321"
fg = "#E8E2D5"
fg_alt = "#DDD5C7"
fg_dim = "#DDD5C7"
fg_dark = "#B5AA95"

# Fog colors (misty grays)
fog_0 = "#171615"
fog_1 = "#252321"
fog_2 = "#34302B"
fog_3 = "#433E36"
fog_4 = "#524C41"

# Gaslight colors (warm amber tones)
gaslight_amber = "#F4C430"
gaslight_yellow = "#FFF8DC"
gaslight_orange = "#D2B48C"

# Cobblestone colors (stone grays)
cobble_gray_1 = "#696969"
cobble_gray_2 = "#778899"
cobble_dark = "#2F4F4F"

# Brick colors (weathered reds and browns)
brick_red = "#B22222"
brick_brown = "#A0522D"
brick_tan = "#D2B48C"

# Thames colors (river blues and greens)
thames_blue = "#4682B4"
thames_green = "#2E8B57"
thames_murky = "#556B2F"

# Victorian colors (period appropriate tones)
victorian_burgundy = "#800020"
victorian_gold = "#DAA520"
victorian_silver = "#C0C0C0"
victorian_navy = "#191970"

# Chimney colors (soot and smoke)
chimney_soot = "#36454F"
chimney_smoke = "#708090"

# Lamppost colors (iron and brass)
iron_black = "#2F2F2F"
brass_yellow = "#B5A642"

# Pea soup colors (thick fog tones)
peasoup_green = "#9ACD32"
peasoup_yellow = "#ADFF2F"

# Carriage colors (leather and wood)
leather_brown = "#8B4513"
mahogany_brown = "#C04000"

# Clock tower colors (stone and bronze)
stone_gray = "#696969"
bronze_gold = "#CD7F32"

# Paper-inspired neutral tones
black = "#0F0E0D"
dark_gray = "#34302B"
gray = "#524C41"
light_gray = "#6B6052"
white = "#E8E2D5"

# Semantic color mappings
blue = "#4682B4"
cyan = "#5F9EA0"
green = "#2E8B57"
yellow = "#DAA520"
orange = "#D2B48C"
red = "#B22222"
purple = "#663399"
magenta = "#8B008B"

# UI colors
border = "#524C41"
selection = "#433E36"
comment = "#6B6052"
line_number = "#524C41"
cursor_line = "#34302B"
cursor_column = "#34302B"
visual = "#433E36"
visual_nc = "#34302B"
search = "#B22222"
inc_search = "#800020"
match_paren = "#DAA520"
cursor_line_nr = "#DDD5C7"
folded = "#524C41"
fold_column = "#524C41"

# Completion menu
pmenu = "#252321"
pmenu_sel = "#433E36"
pmenu_sb = "#171615"
pmenu_thumb = "#524C41"

# Statusline
status_line = "#252321"
status_line_nc = "#171615"

# Tabline
tab_line = "#171615"
tab_line_fill = "#0F0E0D"
tab_line_sel = "#252321"

# Vertical split
vert_split = "#524C41"

# Diff colors
diff_add = "#2E8B57"
diff_delete = "#B22222"
diff_change = "#DAA520"
diff_text = "#D2B48C"

# Git colors
git_add = "#2E8B57"
git_change = "#DAA520"
git_delete = "#B22222"

# Diagnostic colors
error = "#B22222"
warning = "#D2B48C"
info = "#5F9EA0"
hint = "#663399"

# Terminal colors (ANSI)
terminal_black = "#1C1B1A"
terminal_red = "#B22222"
terminal_green = "#2E8B57"
terminal_yellow = "#DAA520"
terminal_blue = "#4682B4"
terminal_magenta = "#663399"
terminal_cyan = "#5F9EA0"
terminal_white = "#E8E2D5"
terminal_bright_black = "#524C41"
terminal_bright_red = "#800020"
terminal_bright_green = "#556B2F"
terminal_bright_yellow = "#F4C430"
terminal_bright_blue = "#778899"
terminal_bright_magenta = "#8B008B"
terminal_bright_cyan = "#5F9EA0"
terminal_bright_white = "#FFF8DC"

[highlights]
# Editor highlights
Normal = { fg = "fg", bg = "bg" }
NormalFloat = { fg = "fg", bg = "bg_alt" }
CursorLine = { bg = "cursor_line" }
CursorColumn = { bg = "cursor_column" }
ColorColumn = { bg = "bg_highlight" }
LineNr = { fg = "line_number" }
CursorLineNr = { fg = "cursor_line_nr", bold = true }
SignColumn = { bg = "bg" }
Folded = { fg = "folded", bg = "bg_highlight" }
FoldColumn = { fg = "fold_column", bg = "bg" }
Visual = { bg = "visual" }
VisualNOS = { bg = "visual_nc" }
Search = { fg = "bg", bg = "search" }
IncSearch = { fg = "bg", bg = "inc_search" }
VertSplit = { fg = "vert_split" }
WinSeparator = { fg = "border" }
StatusLine = { fg = "fg", bg = "status_line" }
StatusLineNC = { fg = "fg_alt", bg = "status_line_nc" }
Pmenu = { fg = "fg", bg = "pmenu" }
PmenuSel = { fg = "bg", bg = "pmenu_sel" }
PmenuSbar = { bg = "pmenu_sb" }
PmenuThumb = { bg = "pmenu_thumb" }
TabLine = { fg = "fg_alt", bg = "tab_line" }
TabLineFill = { bg = "tab_line_fill" }
TabLineSel = { fg = "fg", bg = "tab_line_sel" }

# Syntax highlights
Comment = { fg = "comment", italic = true }
Constant = { fg = "bronze_gold" }
String = { fg = "thames_green" }
Character = { fg = "gaslight_amber" }
Number = { fg = "victorian_gold" }
Boolean = { fg = "brass_yellow" }
Float = { fg = "victorian_gold" }
Identifier = { fg = "fg" }
Function = { fg = "cobble_gray_2" }
Statement = { fg = "victorian_burgundy" }
Conditional = { fg = "chimney_smoke" }
Repeat = { fg = "victorian_burgundy" }
Label = { fg = "chimney_smoke" }
Operator = { fg = "fg" }
Keyword = { fg = "victorian_burgundy" }
Exception = { fg = "error" }
PreProc = { fg = "victorian_burgundy" }
Include = { fg = "victorian_burgundy" }
Define = { fg = "victorian_burgundy" }
Macro = { fg = "victorian_burgundy" }
PreCondit = { fg = "victorian_burgundy" }
Type = { fg = "cobble_gray_2" }
StorageClass = { fg = "cobble_gray_2" }
Structure = { fg = "cobble_gray_2" }
Typedef = { fg = "cobble_gray_2" }
Special = { fg = "bronze_gold" }
SpecialChar = { fg = "brass_yellow" }
Tag = { fg = "chimney_smoke" }
Delimiter = { fg = "stone_gray" }
SpecialComment = { fg = "brick_red" }
Debug = { fg = "error" }
Underlined = { fg = "blue", underline = true }
Ignore = { fg = "comment" }
Error = { fg = "error", bold = true }
Todo = { fg = "yellow", bg = "bg_highlight", bold = true }

# Modern Tree-sitter highlights
TSVariable = { fg = "fg" }
TSVariableBuiltin = { fg = "brass_yellow" }
TSParameter = { fg = "fg_alt" }
TSField = { fg = "cobble_gray_2" }
TSProperty = { fg = "cobble_gray_2" }
TSConstant = { fg = "bronze_gold" }
TSConstBuiltin = { fg = "brass_yellow" }
TSConstMacro = { fg = "bronze_gold" }
TSNamespace = { fg = "cobble_gray_2" }
TSString = { fg = "thames_green" }
TSStringEscape = { fg = "brass_yellow" }
TSStringSpecial = { fg = "brass_yellow" }
TSCharacter = { fg = "gaslight_amber" }
TSCharacterSpecial = { fg = "brass_yellow" }
TSNumber = { fg = "victorian_gold" }
TSBoolean = { fg = "brass_yellow" }
TSFloat = { fg = "victorian_gold" }
TSFunction = { fg = "cobble_gray_2" }
TSFuncBuiltin = { fg = "peasoup_green" }
TSFuncCall = { fg = "cobble_gray_2" }
TSFuncMacro = { fg = "bronze_gold" }
TSMethod = { fg = "cobble_gray_2" }
TSMethodCall = { fg = "cobble_gray_2" }
TSConstructor = { fg = "cobble_gray_2" }
TSOperator = { fg = "fg" }
TSKeyword = { fg = "victorian_burgundy" }
TSKeywordFunction = { fg = "victorian_burgundy" }
TSKeywordOperator = { fg = "victorian_burgundy" }
TSKeywordReturn = { fg = "victorian_burgundy" }
TSConditional = { fg = "chimney_smoke" }
TSRepeat = { fg = "victorian_burgundy" }
TSException = { fg = "error" }
TSType = { fg = "cobble_gray_2" }
TSTypeBuiltin = { fg = "cobble_gray_2" }
TSTypeDefinition = { fg = "cobble_gray_2" }
TSAttribute = { fg = "bronze_gold" }
TSLabel = { fg = "chimney_smoke" }
TSComment = { fg = "comment", italic = true }
TSPunctDelimiter = { fg = "fg" }
TSPunctBracket = { fg = "fg" }
TSPunctSpecial = { fg = "brass_yellow" }
TSTag = { fg = "chimney_smoke" }
TSTagAttribute = { fg = "bronze_gold" }
TSTagDelimiter = { fg = "fg" }

# LSP highlights
LspReferenceText = { bg = "bg_highlight" }
LspReferenceRead = { bg = "bg_highlight" }
LspReferenceWrite = { bg = "bg_highlight" }
LspSignatureActiveParameter = { fg = "yellow", bold = true }

# Diagnostic highlights
DiagnosticError = { fg = "error" }
DiagnosticWarn = { fg = "warning" }
DiagnosticInfo = { fg = "info" }
DiagnosticHint = { fg = "hint" }
DiagnosticUnderlineError = { undercurl = true, sp = "error" }
DiagnosticUnderlineWarn = { undercurl = true, sp = "warning" }
DiagnosticUnderlineInfo = { undercurl = true, sp = "info" }
DiagnosticUnderlineHint = { undercurl = true, sp = "hint" }
DiagnosticVirtualTextError = { fg = "error", bg = "bg_highlight" }
DiagnosticVirtualTextWarn = { fg = "warning", bg = "bg_highlight" }
DiagnosticVirtualTextInfo = { fg = "info", bg = "bg_highlight" }
DiagnosticVirtualTextHint = { fg = "hint", bg = "bg_highlight" }

# Git highlights
DiffAdd = { fg = "diff_add", bg = "bg" }
DiffChange = { fg = "diff_change", bg = "bg" }
DiffDelete = { fg = "diff_delete", bg = "bg" }
DiffText = { fg = "diff_text", bg = "bg_highlight" }
GitSignsAdd = { fg = "git_add" }
GitSignsChange = { fg = "git_change" }
GitSignsDelete = { fg = "git_delete" }
GitSignsCurrentLineBlame = { fg = "comment", italic = true }

# Plugin-specific highlights
# Telescope
TelescopeBorder = { fg = "border" }
TelescopePromptBorder = { fg = "border" }
TelescopeResultsBorder = { fg = "border" }
TelescopePreviewBorder = { fg = "border" }
TelescopeSelection = { bg = "selection" }
TelescopePromptPrefix = { fg = "blue" }
TelescopeMatching = { fg = "yellow", bold = true }

# Neo-tree
NeoTreeDirectoryIcon = { fg = "blue" }
NeoTreeDirectoryName = { fg = "blue" }
NeoTreeFileName = { fg = "fg" }
NeoTreeFileIcon = { fg = "fg_alt" }
NeoTreeRootName = { fg = "purple", bold = true }
NeoTreeModified = { fg = "orange" }
NeoTreeGitAdded = { fg = "git_add" }
NeoTreeGitDeleted = { fg = "git_delete" }
NeoTreeGitModified = { fg = "git_change" }

# Which-key
WhichKeyFloat = { bg = "bg_alt" }
WhichKeyBorder = { fg = "border" }
WhichKey = { fg = "blue" }
WhichKeyGroup = { fg = "purple" }
WhichKeyDesc = { fg = "fg" }
WhichKeySeparator = { fg = "comment" }

# Notify
NotifyERRORBorder = { fg = "error" }
NotifyWARNBorder = { fg = "warning" }
NotifyINFOBorder = { fg = "info" }
NotifyDEBUGBorder = { fg = "comment" }
NotifyTRACEBorder = { fg = "hint" }
NotifyERRORIcon = { fg = "error" }
NotifyWARNIcon = { fg = "warning" }
NotifyINFOIcon = { fg = "info" }
NotifyDEBUGIcon = { fg = "comment" }
NotifyTRACEIcon = { fg = "hint" }

# Nvim-cmp
CmpItemAbbr = { fg = "fg" }
CmpItemAbbrDeprecated = { fg = "comment", strikethrough = true }
CmpItemAbbrMatch = { fg = "blue", bold = true }
CmpItemAbbrMatchFuzzy = { fg = "blue", bold = true }
CmpItemKind = { fg = "purple" }
CmpItemMenu = { fg = "comment" }

# Dashboard
DashboardShortCut = { fg = "blue" }
DashboardHeader = { fg = "purple" }
DashboardCenter = { fg = "green" }
DashboardFooter = { fg = "comment", italic = true }

# Indent Blankline
IndentBlanklineChar = { fg = "fog_3" }
IndentBlanklineContextChar = { fg = "fog_4" }
IndentBlanklineSpaceChar = { fg = "fog_3" }
IndentBlanklineSpaceCharBlankline = { fg = "fog_2" }

# Rainbow delimiters
RainbowDelimiterRed = { fg = "brick_red" }
RainbowDelimiterYellow = { fg = "gaslight_amber" }
RainbowDelimiterBlue = { fg = "thames_blue" }
RainbowDelimiterOrange = { fg = "bronze_gold" }
RainbowDelimiterGreen = { fg = "thames_green" }
RainbowDelimiterViolet = { fg = "purple" }
RainbowDelimiterCyan = { fg = "cyan" }
