# Neon Synthwave - A retro 80s colorscheme
# Inspired by synthwave music, neon grids, and retro-futuristic aesthetics

[metadata]
name = "neon_synthwave"
display_name = "Neon Synthwave"
author = "Claude"
version = "1.0.0"
description = "Retro 80s synthwave colorscheme with vibrant neon colors and grid aesthetics"
background = "dark"

[colors]
# Base colors - Dark synthwave foundations
bg = "#0A0A14"
bg_alt = "#070710"
bg_highlight = "#141428"
bg_dim = "#070710"
bg_light = "#141428"
fg = "#F0F0FF"
fg_alt = "#E0E0F0"
fg_dim = "#E0E0F0"
fg_dark = "#B8B8D8"

# Grid colors (cyber grid backgrounds)
grid_0 = "#070710"
grid_1 = "#141428"
grid_2 = "#1F1F3C"
grid_3 = "#2A2A50"
grid_4 = "#353564"

# Neon colors (bright synthwave palette)
neon_pink = "#FF007F"
neon_cyan = "#00FFFF"
neon_purple = "#BF00FF"
neon_green = "#39FF14"
neon_orange = "#FF8C00"
neon_yellow = "#FFFF00"
neon_red = "#FF073A"
neon_blue = "#0080FF"

# Retro colors (vintage computer tones)
retro_amber = "#FFB000"
retro_green = "#00FF41"
retro_blue = "#0080FF"
retro_magenta = "#FF00FF"

# Synthwave colors (signature palette)
synth_pink_1 = "#FF1493"
synth_pink_2 = "#FF69B4"
synth_purple_1 = "#8A2BE2"
synth_purple_2 = "#9370DB"
synth_cyan_1 = "#00CED1"
synth_cyan_2 = "#20B2AA"

# Vapor colors (vaporwave pastels)
vapor_pink = "#FFB3BA"
vapor_purple = "#BFCFFF"
vapor_mint = "#B4F8C8"
vapor_peach = "#FFDFBA"

# Laser colors (beam effects)
laser_red = "#FF073A"
laser_green = "#39FF14"
laser_blue = "#0080FF"
laser_purple = "#BF00FF"

# Hologram colors (translucent effects)
holo_cyan = "#87CEEB"
holo_pink = "#FFB6C1"
holo_purple = "#DDA0DD"

# Arcade colors (classic game palette)
arcade_red = "#FF073A"
arcade_yellow = "#FFFF00"
arcade_blue = "#0080FF"
arcade_green = "#00FF00"

# Chrome colors (metallic accents)
chrome_silver = "#C0C0C0"
chrome_gold = "#FFD700"

# Paper-inspired neutral tones
black = "#000000"
dark_gray = "#1F1F3C"
gray = "#353564"
light_gray = "#4A4A78"
white = "#F0F0FF"

# Semantic color mappings
blue = "#0080FF"
cyan = "#00FFFF"
green = "#39FF14"
yellow = "#FFFF00"
orange = "#FF8C00"
red = "#FF073A"
purple = "#BF00FF"
magenta = "#FF007F"

# UI colors
border = "#353564"
selection = "#2A2A50"
comment = "#4A4A78"
line_number = "#353564"
cursor_line = "#1F1F3C"
cursor_column = "#1F1F3C"
visual = "#2A2A50"
visual_nc = "#1F1F3C"
search = "#FF007F"
inc_search = "#FF1493"
match_paren = "#FFFF00"
cursor_line_nr = "#E0E0F0"
folded = "#353564"
fold_column = "#353564"

# Completion menu
pmenu = "#141428"
pmenu_sel = "#2A2A50"
pmenu_sb = "#070710"
pmenu_thumb = "#353564"

# Statusline
status_line = "#141428"
status_line_nc = "#070710"

# Tabline
tab_line = "#070710"
tab_line_fill = "#000000"
tab_line_sel = "#141428"

# Vertical split
vert_split = "#353564"

# Diff colors
diff_add = "#39FF14"
diff_delete = "#FF073A"
diff_change = "#FFFF00"
diff_text = "#FF8C00"

# Git colors
git_add = "#39FF14"
git_change = "#FFFF00"
git_delete = "#FF073A"

# Diagnostic colors
error = "#FF073A"
warning = "#FF8C00"
info = "#00FFFF"
hint = "#BF00FF"

# Terminal colors (ANSI)
terminal_black = "#0A0A14"
terminal_red = "#FF073A"
terminal_green = "#39FF14"
terminal_yellow = "#FFFF00"
terminal_blue = "#0080FF"
terminal_magenta = "#BF00FF"
terminal_cyan = "#00FFFF"
terminal_white = "#F0F0FF"
terminal_bright_black = "#353564"
terminal_bright_red = "#FF1493"
terminal_bright_green = "#00FF41"
terminal_bright_yellow = "#FFD700"
terminal_bright_blue = "#1E90FF"
terminal_bright_magenta = "#FF00FF"
terminal_bright_cyan = "#00CED1"
terminal_bright_white = "#FFFFFF"

[highlights]
# Editor highlights
Normal = { fg = "fg", bg = "bg" }
NormalFloat = { fg = "fg", bg = "bg_alt" }
CursorLine = { bg = "cursor_line" }
CursorColumn = { bg = "cursor_column" }
ColorColumn = { bg = "bg_highlight" }
LineNr = { fg = "line_number" }
CursorLineNr = { fg = "cursor_line_nr", bold = true }
SignColumn = { bg = "bg" }
Folded = { fg = "folded", bg = "bg_highlight" }
FoldColumn = { fg = "fold_column", bg = "bg" }
Visual = { bg = "visual" }
VisualNOS = { bg = "visual_nc" }
Search = { fg = "bg", bg = "search" }
IncSearch = { fg = "bg", bg = "inc_search" }
VertSplit = { fg = "vert_split" }
WinSeparator = { fg = "border" }
StatusLine = { fg = "fg", bg = "status_line" }
StatusLineNC = { fg = "fg_alt", bg = "status_line_nc" }
Pmenu = { fg = "fg", bg = "pmenu" }
PmenuSel = { fg = "bg", bg = "pmenu_sel" }
PmenuSbar = { bg = "pmenu_sb" }
PmenuThumb = { bg = "pmenu_thumb" }
TabLine = { fg = "fg_alt", bg = "tab_line" }
TabLineFill = { bg = "tab_line_fill" }
TabLineSel = { fg = "fg", bg = "tab_line_sel" }

# Syntax highlights
Comment = { fg = "comment", italic = true }
Constant = { fg = "chrome_gold" }
String = { fg = "neon_green" }
Character = { fg = "neon_yellow" }
Number = { fg = "neon_cyan" }
Boolean = { fg = "neon_purple" }
Float = { fg = "neon_cyan" }
Identifier = { fg = "fg" }
Function = { fg = "synth_cyan_1" }
Statement = { fg = "neon_pink" }
Conditional = { fg = "synth_purple_1" }
Repeat = { fg = "neon_pink" }
Label = { fg = "synth_purple_1" }
Operator = { fg = "fg" }
Keyword = { fg = "neon_pink" }
Exception = { fg = "error" }
PreProc = { fg = "neon_pink" }
Include = { fg = "neon_pink" }
Define = { fg = "neon_pink" }
Macro = { fg = "neon_pink" }
PreCondit = { fg = "neon_pink" }
Type = { fg = "synth_cyan_1" }
StorageClass = { fg = "synth_cyan_1" }
Structure = { fg = "synth_cyan_1" }
Typedef = { fg = "synth_cyan_1" }
Special = { fg = "chrome_gold" }
SpecialChar = { fg = "neon_purple" }
Tag = { fg = "synth_purple_1" }
Delimiter = { fg = "holo_purple" }
SpecialComment = { fg = "laser_red" }
Debug = { fg = "error" }
Underlined = { fg = "blue", underline = true }
Ignore = { fg = "comment" }
Error = { fg = "error", bold = true }
Todo = { fg = "yellow", bg = "bg_highlight", bold = true }

# Modern Tree-sitter highlights
TSVariable = { fg = "fg" }
TSVariableBuiltin = { fg = "neon_purple" }
TSParameter = { fg = "fg_alt" }
TSField = { fg = "synth_cyan_1" }
TSProperty = { fg = "synth_cyan_1" }
TSConstant = { fg = "chrome_gold" }
TSConstBuiltin = { fg = "neon_purple" }
TSConstMacro = { fg = "chrome_gold" }
TSNamespace = { fg = "synth_cyan_1" }
TSString = { fg = "neon_green" }
TSStringEscape = { fg = "neon_purple" }
TSStringSpecial = { fg = "neon_purple" }
TSCharacter = { fg = "neon_yellow" }
TSCharacterSpecial = { fg = "neon_purple" }
TSNumber = { fg = "neon_cyan" }
TSBoolean = { fg = "neon_purple" }
TSFloat = { fg = "neon_cyan" }
TSFunction = { fg = "synth_cyan_1" }
TSFuncBuiltin = { fg = "vapor_mint" }
TSFuncCall = { fg = "synth_cyan_1" }
TSFuncMacro = { fg = "chrome_gold" }
TSMethod = { fg = "synth_cyan_1" }
TSMethodCall = { fg = "synth_cyan_1" }
TSConstructor = { fg = "synth_cyan_1" }
TSOperator = { fg = "fg" }
TSKeyword = { fg = "neon_pink" }
TSKeywordFunction = { fg = "neon_pink" }
TSKeywordOperator = { fg = "neon_pink" }
TSKeywordReturn = { fg = "neon_pink" }
TSConditional = { fg = "synth_purple_1" }
TSRepeat = { fg = "neon_pink" }
TSException = { fg = "error" }
TSType = { fg = "synth_cyan_1" }
TSTypeBuiltin = { fg = "synth_cyan_1" }
TSTypeDefinition = { fg = "synth_cyan_1" }
TSAttribute = { fg = "chrome_gold" }
TSLabel = { fg = "synth_purple_1" }
TSComment = { fg = "comment", italic = true }
TSPunctDelimiter = { fg = "fg" }
TSPunctBracket = { fg = "fg" }
TSPunctSpecial = { fg = "neon_purple" }
TSTag = { fg = "synth_purple_1" }
TSTagAttribute = { fg = "chrome_gold" }
TSTagDelimiter = { fg = "fg" }

# LSP highlights
LspReferenceText = { bg = "bg_highlight" }
LspReferenceRead = { bg = "bg_highlight" }
LspReferenceWrite = { bg = "bg_highlight" }
LspSignatureActiveParameter = { fg = "yellow", bold = true }

# Diagnostic highlights
DiagnosticError = { fg = "error" }
DiagnosticWarn = { fg = "warning" }
DiagnosticInfo = { fg = "info" }
DiagnosticHint = { fg = "hint" }
DiagnosticUnderlineError = { undercurl = true, sp = "error" }
DiagnosticUnderlineWarn = { undercurl = true, sp = "warning" }
DiagnosticUnderlineInfo = { undercurl = true, sp = "info" }
DiagnosticUnderlineHint = { undercurl = true, sp = "hint" }
DiagnosticVirtualTextError = { fg = "error", bg = "bg_highlight" }
DiagnosticVirtualTextWarn = { fg = "warning", bg = "bg_highlight" }
DiagnosticVirtualTextInfo = { fg = "info", bg = "bg_highlight" }
DiagnosticVirtualTextHint = { fg = "hint", bg = "bg_highlight" }

# Git highlights
DiffAdd = { fg = "diff_add", bg = "bg" }
DiffChange = { fg = "diff_change", bg = "bg" }
DiffDelete = { fg = "diff_delete", bg = "bg" }
DiffText = { fg = "diff_text", bg = "bg_highlight" }
GitSignsAdd = { fg = "git_add" }
GitSignsChange = { fg = "git_change" }
GitSignsDelete = { fg = "git_delete" }
GitSignsCurrentLineBlame = { fg = "comment", italic = true }

# Plugin-specific highlights
# Telescope
TelescopeBorder = { fg = "border" }
TelescopePromptBorder = { fg = "border" }
TelescopeResultsBorder = { fg = "border" }
TelescopePreviewBorder = { fg = "border" }
TelescopeSelection = { bg = "selection" }
TelescopePromptPrefix = { fg = "blue" }
TelescopeMatching = { fg = "yellow", bold = true }

# Neo-tree
NeoTreeDirectoryIcon = { fg = "blue" }
NeoTreeDirectoryName = { fg = "blue" }
NeoTreeFileName = { fg = "fg" }
NeoTreeFileIcon = { fg = "fg_alt" }
NeoTreeRootName = { fg = "purple", bold = true }
NeoTreeModified = { fg = "orange" }
NeoTreeGitAdded = { fg = "git_add" }
NeoTreeGitDeleted = { fg = "git_delete" }
NeoTreeGitModified = { fg = "git_change" }

# Which-key
WhichKeyFloat = { bg = "bg_alt" }
WhichKeyBorder = { fg = "border" }
WhichKey = { fg = "blue" }
WhichKeyGroup = { fg = "purple" }
WhichKeyDesc = { fg = "fg" }
WhichKeySeparator = { fg = "comment" }

# Notify
NotifyERRORBorder = { fg = "error" }
NotifyWARNBorder = { fg = "warning" }
NotifyINFOBorder = { fg = "info" }
NotifyDEBUGBorder = { fg = "comment" }
NotifyTRACEBorder = { fg = "hint" }
NotifyERRORIcon = { fg = "error" }
NotifyWARNIcon = { fg = "warning" }
NotifyINFOIcon = { fg = "info" }
NotifyDEBUGIcon = { fg = "comment" }
NotifyTRACEIcon = { fg = "hint" }

# Nvim-cmp
CmpItemAbbr = { fg = "fg" }
CmpItemAbbrDeprecated = { fg = "comment", strikethrough = true }
CmpItemAbbrMatch = { fg = "blue", bold = true }
CmpItemAbbrMatchFuzzy = { fg = "blue", bold = true }
CmpItemKind = { fg = "purple" }
CmpItemMenu = { fg = "comment" }

# Dashboard
DashboardShortCut = { fg = "blue" }
DashboardHeader = { fg = "purple" }
DashboardCenter = { fg = "green" }
DashboardFooter = { fg = "comment", italic = true }

# Indent Blankline
IndentBlanklineChar = { fg = "grid_3" }
IndentBlanklineContextChar = { fg = "grid_4" }
IndentBlanklineSpaceChar = { fg = "grid_3" }
IndentBlanklineSpaceCharBlankline = { fg = "grid_2" }

# Rainbow delimiters
RainbowDelimiterRed = { fg = "laser_red" }
RainbowDelimiterYellow = { fg = "neon_yellow" }
RainbowDelimiterBlue = { fg = "laser_blue" }
RainbowDelimiterOrange = { fg = "neon_orange" }
RainbowDelimiterGreen = { fg = "neon_green" }
RainbowDelimiterViolet = { fg = "neon_purple" }
RainbowDelimiterCyan = { fg = "neon_cyan" }
