# Nordic Frost - A cool winter colorscheme
# Inspired by Scandinavian winters, aurora borealis, and frozen landscapes

[metadata]
name = "nordic_frost"
display_name = "Nordic Frost"
author = "Claude"
version = "1.0.0"
description = "Cool winter colorscheme inspired by Scandinavian landscapes and aurora borealis"
background = "dark"

[colors]
# Base colors - Winter foundations
bg = "#0F1419"
bg_alt = "#0B0F14"
bg_highlight = "#1A1F26"
bg_dim = "#0B0F14"
bg_light = "#1A1F26"
fg = "#E5E9F0"
fg_alt = "#D8DEE9"
fg_dim = "#D8DEE9"
fg_dark = "#AEBACB"

# Ice colors (cool grays and whites)
ice_0 = "#0B0F14"
ice_1 = "#1A1F26"
ice_2 = "#242B35"
ice_3 = "#2E3440"
ice_4 = "#434C5E"

# Snow colors (pure whites and off-whites)
snow_white = "#ECEFF4"
snow_gray = "#E5E9F0"

# Frost colors (cool blues)
frost_blue_1 = "#1B2B3A"
frost_blue_2 = "#2F4358"
frost_aqua_1 = "#5E81AC"
frost_aqua_2 = "#81A1C1"

# Aurora colors (northern lights pastels)
aurora_green = "#A3BE8C"
aurora_pink = "#B48EAD"
aurora_blue = "#88C0D0"
aurora_purple = "#B48EAD"

# Pine colors (muted forest greens)
pine_green = "#8FBCBB"
pine_dark = "#5E7F7E"

# Winter colors (cool earth tones)
winter_blue = "#5E81AC"
winter_red = "#BF616A"
winter_yellow = "#EBCB8B"

# Mountain colors (cool grays)
mountain_blue = "#81A1C1"
mountain_gray = "#4C566A"

# Crystal colors (bright accents)
crystal_blue = "#88C0D0"
crystal_white = "#ECEFF4"

# Glacier colors (icy blues)
glacier_blue_1 = "#5E81AC"
glacier_blue_2 = "#81A1C1"

# Arctic colors (frozen tones)
arctic_white = "#ECEFF4"
arctic_blue = "#88C0D0"

# Twilight colors (evening blues)
twilight_blue = "#434C5E"
twilight_purple = "#B48EAD"

# Paper-inspired neutral tones
black = "#0B0F14"
dark_gray = "#2E3440"
gray = "#434C5E"
light_gray = "#4C566A"
white = "#ECEFF4"

# Semantic color mappings
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
yellow = "#EBCB8B"
orange = "#D08770"
red = "#BF616A"
purple = "#B48EAD"
magenta = "#B48EAD"

# UI colors
border = "#434C5E"
selection = "#2F4358"
comment = "#4C566A"
line_number = "#434C5E"
cursor_line = "#242B35"
cursor_column = "#242B35"
visual = "#2F4358"
visual_nc = "#1B2B3A"
search = "#BF616A"
inc_search = "#D08770"
match_paren = "#EBCB8B"
cursor_line_nr = "#D8DEE9"
folded = "#434C5E"
fold_column = "#434C5E"

# Completion menu
pmenu = "#1A1F26"
pmenu_sel = "#2F4358"
pmenu_sb = "#0B0F14"
pmenu_thumb = "#434C5E"

# Statusline
status_line = "#1A1F26"
status_line_nc = "#0B0F14"

# Tabline
tab_line = "#0B0F14"
tab_line_fill = "#0F1419"
tab_line_sel = "#1A1F26"

# Vertical split
vert_split = "#434C5E"

# Diff colors
diff_add = "#A3BE8C"
diff_delete = "#BF616A"
diff_change = "#EBCB8B"
diff_text = "#D08770"

# Git colors
git_add = "#A3BE8C"
git_change = "#EBCB8B"
git_delete = "#BF616A"

# Diagnostic colors
error = "#BF616A"
warning = "#D08770"
info = "#88C0D0"
hint = "#B48EAD"

# Terminal colors (ANSI)
terminal_black = "#0F1419"
terminal_red = "#BF616A"
terminal_green = "#A3BE8C"
terminal_yellow = "#EBCB8B"
terminal_blue = "#81A1C1"
terminal_magenta = "#B48EAD"
terminal_cyan = "#88C0D0"
terminal_white = "#E5E9F0"
terminal_bright_black = "#434C5E"
terminal_bright_red = "#D08770"
terminal_bright_green = "#8FBCBB"
terminal_bright_yellow = "#ECEFF4"
terminal_bright_blue = "#5E81AC"
terminal_bright_magenta = "#B48EAD"
terminal_bright_cyan = "#88C0D0"
terminal_bright_white = "#ECEFF4"

[highlights]
# Editor highlights
Normal = { fg = "fg", bg = "bg" }
NormalFloat = { fg = "fg", bg = "bg_alt" }
CursorLine = { bg = "cursor_line" }
CursorColumn = { bg = "cursor_column" }
ColorColumn = { bg = "bg_highlight" }
LineNr = { fg = "line_number" }
CursorLineNr = { fg = "cursor_line_nr", bold = true }
SignColumn = { bg = "bg" }
Folded = { fg = "folded", bg = "bg_highlight" }
FoldColumn = { fg = "fold_column", bg = "bg" }
Visual = { bg = "visual" }
VisualNOS = { bg = "visual_nc" }
Search = { fg = "bg", bg = "search" }
IncSearch = { fg = "bg", bg = "inc_search" }
VertSplit = { fg = "vert_split" }
WinSeparator = { fg = "border" }
StatusLine = { fg = "fg", bg = "status_line" }
StatusLineNC = { fg = "fg_alt", bg = "status_line_nc" }
Pmenu = { fg = "fg", bg = "pmenu" }
PmenuSel = { fg = "bg", bg = "pmenu_sel" }
PmenuSbar = { bg = "pmenu_sb" }
PmenuThumb = { bg = "pmenu_thumb" }
TabLine = { fg = "fg_alt", bg = "tab_line" }
TabLineFill = { bg = "tab_line_fill" }
TabLineSel = { fg = "fg", bg = "tab_line_sel" }

# Syntax highlights
Comment = { fg = "comment", italic = true }
Constant = { fg = "aurora_blue" }
String = { fg = "aurora_green" }
Character = { fg = "winter_yellow" }
Number = { fg = "crystal_blue" }
Boolean = { fg = "aurora_pink" }
Float = { fg = "crystal_blue" }
Identifier = { fg = "fg" }
Function = { fg = "glacier_blue_2" }
Statement = { fg = "winter_blue" }
Conditional = { fg = "aurora_pink" }
Repeat = { fg = "winter_blue" }
Label = { fg = "aurora_pink" }
Operator = { fg = "fg" }
Keyword = { fg = "winter_blue" }
Exception = { fg = "error" }
PreProc = { fg = "winter_blue" }
Include = { fg = "winter_blue" }
Define = { fg = "winter_blue" }
Macro = { fg = "winter_blue" }
PreCondit = { fg = "winter_blue" }
Type = { fg = "glacier_blue_2" }
StorageClass = { fg = "glacier_blue_2" }
Structure = { fg = "glacier_blue_2" }
Typedef = { fg = "glacier_blue_2" }
Special = { fg = "aurora_blue" }
SpecialChar = { fg = "aurora_pink" }
Tag = { fg = "aurora_pink" }
Delimiter = { fg = "twilight_purple" }
SpecialComment = { fg = "winter_red" }
Debug = { fg = "error" }
Underlined = { fg = "blue", underline = true }
Ignore = { fg = "comment" }
Error = { fg = "error", bold = true }
Todo = { fg = "yellow", bg = "bg_highlight", bold = true }

# Modern Tree-sitter highlights
TSVariable = { fg = "fg" }
TSVariableBuiltin = { fg = "aurora_pink" }
TSParameter = { fg = "fg_alt" }
TSField = { fg = "glacier_blue_2" }
TSProperty = { fg = "glacier_blue_2" }
TSConstant = { fg = "aurora_blue" }
TSConstBuiltin = { fg = "aurora_pink" }
TSConstMacro = { fg = "aurora_blue" }
TSNamespace = { fg = "glacier_blue_2" }
TSString = { fg = "aurora_green" }
TSStringEscape = { fg = "aurora_pink" }
TSStringSpecial = { fg = "aurora_pink" }
TSCharacter = { fg = "winter_yellow" }
TSCharacterSpecial = { fg = "aurora_pink" }
TSNumber = { fg = "crystal_blue" }
TSBoolean = { fg = "aurora_pink" }
TSFloat = { fg = "crystal_blue" }
TSFunction = { fg = "glacier_blue_2" }
TSFuncBuiltin = { fg = "pine_green" }
TSFuncCall = { fg = "glacier_blue_2" }
TSFuncMacro = { fg = "aurora_blue" }
TSMethod = { fg = "glacier_blue_2" }
TSMethodCall = { fg = "glacier_blue_2" }
TSConstructor = { fg = "glacier_blue_2" }
TSOperator = { fg = "fg" }
TSKeyword = { fg = "winter_blue" }
TSKeywordFunction = { fg = "winter_blue" }
TSKeywordOperator = { fg = "winter_blue" }
TSKeywordReturn = { fg = "winter_blue" }
TSConditional = { fg = "aurora_pink" }
TSRepeat = { fg = "winter_blue" }
TSException = { fg = "error" }
TSType = { fg = "glacier_blue_2" }
TSTypeBuiltin = { fg = "glacier_blue_2" }
TSTypeDefinition = { fg = "glacier_blue_2" }
TSAttribute = { fg = "aurora_blue" }
TSLabel = { fg = "aurora_pink" }
TSComment = { fg = "comment", italic = true }
TSPunctDelimiter = { fg = "fg" }
TSPunctBracket = { fg = "fg" }
TSPunctSpecial = { fg = "aurora_pink" }
TSTag = { fg = "aurora_pink" }
TSTagAttribute = { fg = "aurora_blue" }
TSTagDelimiter = { fg = "fg" }

# LSP highlights
LspReferenceText = { bg = "bg_highlight" }
LspReferenceRead = { bg = "bg_highlight" }
LspReferenceWrite = { bg = "bg_highlight" }
LspSignatureActiveParameter = { fg = "yellow", bold = true }

# Diagnostic highlights
DiagnosticError = { fg = "error" }
DiagnosticWarn = { fg = "warning" }
DiagnosticInfo = { fg = "info" }
DiagnosticHint = { fg = "hint" }
DiagnosticUnderlineError = { undercurl = true, sp = "error" }
DiagnosticUnderlineWarn = { undercurl = true, sp = "warning" }
DiagnosticUnderlineInfo = { undercurl = true, sp = "info" }
DiagnosticUnderlineHint = { undercurl = true, sp = "hint" }
DiagnosticVirtualTextError = { fg = "error", bg = "bg_highlight" }
DiagnosticVirtualTextWarn = { fg = "warning", bg = "bg_highlight" }
DiagnosticVirtualTextInfo = { fg = "info", bg = "bg_highlight" }
DiagnosticVirtualTextHint = { fg = "hint", bg = "bg_highlight" }

# Git highlights
DiffAdd = { fg = "diff_add", bg = "bg" }
DiffChange = { fg = "diff_change", bg = "bg" }
DiffDelete = { fg = "diff_delete", bg = "bg" }
DiffText = { fg = "diff_text", bg = "bg_highlight" }
GitSignsAdd = { fg = "git_add" }
GitSignsChange = { fg = "git_change" }
GitSignsDelete = { fg = "git_delete" }
GitSignsCurrentLineBlame = { fg = "comment", italic = true }

# Plugin-specific highlights
# Telescope
TelescopeBorder = { fg = "border" }
TelescopePromptBorder = { fg = "border" }
TelescopeResultsBorder = { fg = "border" }
TelescopePreviewBorder = { fg = "border" }
TelescopeSelection = { bg = "selection" }
TelescopePromptPrefix = { fg = "blue" }
TelescopeMatching = { fg = "yellow", bold = true }

# Neo-tree
NeoTreeDirectoryIcon = { fg = "blue" }
NeoTreeDirectoryName = { fg = "blue" }
NeoTreeFileName = { fg = "fg" }
NeoTreeFileIcon = { fg = "fg_alt" }
NeoTreeRootName = { fg = "purple", bold = true }
NeoTreeModified = { fg = "orange" }
NeoTreeGitAdded = { fg = "git_add" }
NeoTreeGitDeleted = { fg = "git_delete" }
NeoTreeGitModified = { fg = "git_change" }

# Which-key
WhichKeyFloat = { bg = "bg_alt" }
WhichKeyBorder = { fg = "border" }
WhichKey = { fg = "blue" }
WhichKeyGroup = { fg = "purple" }
WhichKeyDesc = { fg = "fg" }
WhichKeySeparator = { fg = "comment" }

# Notify
NotifyERRORBorder = { fg = "error" }
NotifyWARNBorder = { fg = "warning" }
NotifyINFOBorder = { fg = "info" }
NotifyDEBUGBorder = { fg = "comment" }
NotifyTRACEBorder = { fg = "hint" }
NotifyERRORIcon = { fg = "error" }
NotifyWARNIcon = { fg = "warning" }
NotifyINFOIcon = { fg = "info" }
NotifyDEBUGIcon = { fg = "comment" }
NotifyTRACEIcon = { fg = "hint" }

# Nvim-cmp
CmpItemAbbr = { fg = "fg" }
CmpItemAbbrDeprecated = { fg = "comment", strikethrough = true }
CmpItemAbbrMatch = { fg = "blue", bold = true }
CmpItemAbbrMatchFuzzy = { fg = "blue", bold = true }
CmpItemKind = { fg = "purple" }
CmpItemMenu = { fg = "comment" }

# Dashboard
DashboardShortCut = { fg = "blue" }
DashboardHeader = { fg = "purple" }
DashboardCenter = { fg = "green" }
DashboardFooter = { fg = "comment", italic = true }

# Indent Blankline
IndentBlanklineChar = { fg = "ice_3" }
IndentBlanklineContextChar = { fg = "ice_4" }
IndentBlanklineSpaceChar = { fg = "ice_3" }
IndentBlanklineSpaceCharBlankline = { fg = "ice_2" }

# Rainbow delimiters
RainbowDelimiterRed = { fg = "winter_red" }
RainbowDelimiterYellow = { fg = "winter_yellow" }
RainbowDelimiterBlue = { fg = "crystal_blue" }
RainbowDelimiterOrange = { fg = "orange" }
RainbowDelimiterGreen = { fg = "aurora_green" }
RainbowDelimiterViolet = { fg = "aurora_purple" }
RainbowDelimiterCyan = { fg = "aurora_blue" }
