# Winter Pine - A deep evergreen colorscheme
# Dark evergreen with warm amber and dusty rose
# Inspired by snow-laden pine forests and winter warmth

[metadata]
name = "winter_pine"
display_name = "Winter Pine"
author = "custom"
version = "1.0.0"
description = "Deep evergreen colorscheme with warm amber and dusty rose"
background = "dark"

[colors]
# Base colors - Core backgrounds and foregrounds
bg = "#0F1A0F"
bg_alt = "#0B140B"
bg_highlight = "#18241C"
bg_dim = "#0B140B"
bg_light = "#18241C"
fg = "#D4E0D4"
fg_alt = "#BAC7B5"
fg_dim = "#BAC7B5"
fg_dark = "#A0AE98"

# Pine colors (deep greens)
pine_deep = "#1B2F1B"
pine_dark = "#2C4A2C"
pine_medium = "#3D5F3D"
pine_light = "#4F734F"
pine_sage = "#668B66"

# Forest colors (evergreen variations)
forest_shadow = "#0A1A0F"
forest_deep = "#162A1B"
forest_moss = "#2F4A35"
forest_fern = "#4A664F"

# Snow colors (cool whites and grays)
snow_white = "#F0F8F0"
snow_gray = "#D4E0D4"
snow_blue = "#C8D6D4"
snow_mist = "#B8C8B8"

# Amber colors (warm accents)
amber_dark = "#CC8800"
amber_bright = "#E6A500"
amber_gold = "#FFB84D"
amber_honey = "#D4AF37"

# Rose colors (dusty pinks)
rose_dust = "#C7969C"
rose_muted = "#B8878F"
rose_deep = "#A67882"
rose_soft = "#D4A8B0"

# Bark colors (brown tones)
bark_dark = "#4A3829"
bark_medium = "#5D4A3A"
bark_light = "#70564A"

# Winter colors (cool tones)
winter_blue = "#5A7A8A"
winter_gray = "#6B7B7B"
winter_ice = "#A8C8D8"

# Paper-inspired neutral tones
black = "#050A05"
dark_gray = "#2C352C"
gray = "#5A665A"
light_gray = "#7B847B"
white = "#D4E0D4"

# Semantic color mappings
blue = "#5A7A8A"
cyan = "#6B8A8A"
green = "#668B66"
yellow = "#E6A500"
orange = "#CC8800"
red = "#B87882"
purple = "#9B8AA5"
magenta = "#A895A8"

# UI colors
border = "#5A665A"
selection = "#2C4A2C"
comment = "#7B847B"
line_number = "#5A665A"
cursor_line = "#2C352C"
cursor_column = "#2C352C"
visual = "#2C4A2C"
visual_nc = "#2F4A35"
search = "#A67882"
inc_search = "#B87882"
match_paren = "#E6A500"
cursor_line_nr = "#BAC7B5"
folded = "#5A665A"
fold_column = "#5A665A"

# Completion menu
pmenu = "#18241C"
pmenu_sel = "#2C4A2C"
pmenu_sb = "#0B140B"
pmenu_thumb = "#5A665A"

# Statusline
status_line = "#18241C"
status_line_nc = "#0B140B"

# Tabline
tab_line = "#0B140B"
tab_line_fill = "#050A05"
tab_line_sel = "#18241C"

# Vertical split
vert_split = "#5A665A"

# Diff colors
diff_add = "#668B66"
diff_delete = "#A67882"
diff_change = "#E6A500"
diff_text = "#FFB84D"

# Git colors
git_add = "#668B66"
git_change = "#E6A500"
git_delete = "#B87882"

# Diagnostic colors
error = "#B87882"
warning = "#CC8800"
info = "#6B8A8A"
hint = "#A895A8"

# Terminal colors (ANSI)
terminal_black = "#050A05"
terminal_red = "#A67882"
terminal_green = "#668B66"
terminal_yellow = "#E6A500"
terminal_blue = "#5A7A8A"
terminal_magenta = "#9B8AA5"
terminal_cyan = "#6B8A8A"
terminal_white = "#D4E0D4"
terminal_bright_black = "#5A665A"
terminal_bright_red = "#B87882"
terminal_bright_green = "#7A996F"
terminal_bright_yellow = "#FFB84D"
terminal_bright_blue = "#7B9BAB"
terminal_bright_magenta = "#A895A8"
terminal_bright_cyan = "#6B8A8A"
terminal_bright_white = "#BAC7B5"

[highlights]
# Editor highlights
Normal = { fg = "fg", bg = "bg" }
NormalFloat = { fg = "fg", bg = "bg_alt" }
CursorLine = { bg = "cursor_line" }
CursorColumn = { bg = "cursor_column" }
ColorColumn = { bg = "bg_highlight" }
LineNr = { fg = "line_number" }
CursorLineNr = { fg = "cursor_line_nr", bold = true }
SignColumn = { bg = "bg" }
Folded = { fg = "folded", bg = "bg_highlight" }
FoldColumn = { fg = "fold_column", bg = "bg" }
Visual = { bg = "visual" }
VisualNOS = { bg = "visual_nc" }
Search = { fg = "bg", bg = "search" }
IncSearch = { fg = "bg", bg = "inc_search" }
VertSplit = { fg = "vert_split" }
WinSeparator = { fg = "border" }
StatusLine = { fg = "fg", bg = "status_line" }
StatusLineNC = { fg = "fg_alt", bg = "status_line_nc" }
Pmenu = { fg = "fg", bg = "pmenu" }
PmenuSel = { fg = "bg", bg = "pmenu_sel" }
PmenuSbar = { bg = "pmenu_sb" }
PmenuThumb = { bg = "pmenu_thumb" }
TabLine = { fg = "fg_alt", bg = "tab_line" }
TabLineFill = { bg = "tab_line_fill" }
TabLineSel = { fg = "fg", bg = "tab_line_sel" }

# Syntax highlights - Traditional vim groups
Comment = { fg = "comment", italic = true }
Constant = { fg = "amber_bright" }
String = { fg = "green" }
Character = { fg = "amber_gold" }
Number = { fg = "amber_honey" }
Boolean = { fg = "amber_dark" }
Float = { fg = "amber_honey" }
Identifier = { fg = "fg" }
Function = { fg = "pine_sage" }
Statement = { fg = "purple" }
Conditional = { fg = "bark_light" }
Repeat = { fg = "purple" }
Label = { fg = "bark_light" }
Operator = { fg = "fg" }
Keyword = { fg = "purple" }
Exception = { fg = "error" }
PreProc = { fg = "purple" }
Include = { fg = "purple" }
Define = { fg = "purple" }
Macro = { fg = "purple" }
PreCondit = { fg = "purple" }
Type = { fg = "pine_sage" }
StorageClass = { fg = "pine_sage" }
Structure = { fg = "pine_sage" }
Typedef = { fg = "pine_sage" }
Special = { fg = "amber_bright" }
SpecialChar = { fg = "amber_dark" }
Tag = { fg = "bark_light" }
Delimiter = { fg = "magenta" }
SpecialComment = { fg = "rose_deep" }
Debug = { fg = "error" }
Underlined = { fg = "blue", underline = true }
Ignore = { fg = "comment" }
Error = { fg = "error", bold = true }
Todo = { fg = "yellow", bg = "bg_highlight", bold = true }

# Modern Tree-sitter highlights (TS* groups)
TSVariable = { fg = "fg" }
TSVariableBuiltin = { fg = "amber_dark" }
TSParameter = { fg = "fg_alt" }
TSField = { fg = "pine_sage" }
TSProperty = { fg = "pine_sage" }
TSConstant = { fg = "amber_bright" }
TSConstBuiltin = { fg = "amber_dark" }
TSConstMacro = { fg = "amber_bright" }
TSNamespace = { fg = "pine_sage" }
TSString = { fg = "green" }
TSStringEscape = { fg = "amber_dark" }
TSStringSpecial = { fg = "amber_dark" }
TSCharacter = { fg = "amber_gold" }
TSCharacterSpecial = { fg = "amber_dark" }
TSNumber = { fg = "amber_honey" }
TSBoolean = { fg = "amber_dark" }
TSFloat = { fg = "amber_honey" }
TSFunction = { fg = "pine_sage" }
TSFuncBuiltin = { fg = "cyan" }
TSFuncCall = { fg = "pine_sage" }
TSFuncMacro = { fg = "amber_bright" }
TSMethod = { fg = "pine_sage" }
TSMethodCall = { fg = "pine_sage" }
TSConstructor = { fg = "pine_sage" }
TSOperator = { fg = "fg" }
TSKeyword = { fg = "purple" }
TSKeywordFunction = { fg = "purple" }
TSKeywordOperator = { fg = "purple" }
TSKeywordReturn = { fg = "purple" }
TSConditional = { fg = "bark_light" }
TSRepeat = { fg = "purple" }
TSException = { fg = "error" }
TSType = { fg = "pine_sage" }
TSTypeBuiltin = { fg = "pine_sage" }
TSTypeDefinition = { fg = "pine_sage" }
TSAttribute = { fg = "amber_bright" }
TSLabel = { fg = "bark_light" }
TSComment = { fg = "comment", italic = true }
TSPunctDelimiter = { fg = "fg" }
TSPunctBracket = { fg = "fg" }
TSPunctSpecial = { fg = "amber_dark" }
TSTag = { fg = "bark_light" }
TSTagAttribute = { fg = "amber_bright" }
TSTagDelimiter = { fg = "fg" }

# LSP highlights
LspReferenceText = { bg = "bg_highlight" }
LspReferenceRead = { bg = "bg_highlight" }
LspReferenceWrite = { bg = "bg_highlight" }
LspSignatureActiveParameter = { fg = "yellow", bold = true }

# Diagnostic highlights
DiagnosticError = { fg = "error" }
DiagnosticWarn = { fg = "warning" }
DiagnosticInfo = { fg = "info" }
DiagnosticHint = { fg = "hint" }
DiagnosticUnderlineError = { undercurl = true, sp = "error" }
DiagnosticUnderlineWarn = { undercurl = true, sp = "warning" }
DiagnosticUnderlineInfo = { undercurl = true, sp = "info" }
DiagnosticUnderlineHint = { undercurl = true, sp = "hint" }
DiagnosticVirtualTextError = { fg = "error", bg = "bg_highlight" }
DiagnosticVirtualTextWarn = { fg = "warning", bg = "bg_highlight" }
DiagnosticVirtualTextInfo = { fg = "info", bg = "bg_highlight" }
DiagnosticVirtualTextHint = { fg = "hint", bg = "bg_highlight" }

# Git highlights
DiffAdd = { fg = "diff_add", bg = "bg" }
DiffChange = { fg = "diff_change", bg = "bg" }
DiffDelete = { fg = "diff_delete", bg = "bg" }
DiffText = { fg = "diff_text", bg = "bg_highlight" }
GitSignsAdd = { fg = "git_add" }
GitSignsChange = { fg = "git_change" }
GitSignsDelete = { fg = "git_delete" }
GitSignsCurrentLineBlame = { fg = "comment", italic = true }
