local raphael = require("raphael")

return {
	"mavantgarderc/raphael.nvim",
	lazy = false,

	keys = {
		{
			"<leader>tp",
			function()
				raphael.open_picker({ only_configured = true })
			end,
			desc = "Raphael: Configured themes",
		},
		{
			"<leader>t/",
			function()
				raphael.open_picker({ exclude_configured = true })
			end,
			desc = "Raphael: All other themes",
		},
		{
			"<leader>ta",
			function()
				raphael.toggle_auto()
			end,
			desc = "Raphael: Toggle auto-apply",
		},
		{
			"<leader>tR",
			function()
				raphael.refresh_and_reload()
			end,
			desc = "Raphael: Refresh themes",
		},
		{
			"<leader>ts",
			function()
				raphael.show_status()
			end,
			desc = "Raphael: Show status",
		},
	},

	opts = {
		-- default_theme = "kanagawa-paper-edo",

		enable_picker = true,
		bookmark_group = true,
		recent_group = false,
		enable_autocmds = true,
		enable_commands = true,
		project_overrides_filetype = true,
		filetype_overrides_project = false,

		icons = {
			BOOKMARK = "[B]",
			CURRENT_ON = "=> ",
			CURRENT_OFF = " ",
			GROUP_EXPANDED = "[-]",
			GROUP_COLLAPSED = "[+]",
		},

		enable_keymaps = true,
		leader = "<leader>t",
		mappings = {
			picker = "p",
			next = ">",
			previous = "<",
			others = "/",
			auto = "a",
			refresh = "R",
			status = "s",
			random = "r",
		},

		profiles = {
			work = {
				default_theme = "kanagawa-paper-edo",
			},
			night = {
				default_theme = "detox-ink",
			},
			presentation = {
				default_theme = "kanagawa-paper-obsidian",
			},
		},
		current_profile = "work",

		sample_preview = {
			enabled = true,
			relative_size = 0.5,
			languages = {
				"lua",
				"python",
				"javascript",
				"rust",
				"go",
				"ruby",
				"sh",
				"sql",
			},
		},

		theme_aliases = {
			-- ["kanagawa-paper-sunset"] = "Kanagawa (Paper SUNSET)",
		},
		group_aliases = {
			dc = "Distant Colors",
			emotional_entities = "Emotional Entities",
		},

		theme_map = {
			dc = {
				arkham_asylum = {
					"arkham-asylum-amadeus-arkham",
					"arkham-asylum-black-mask",
					"arkham-asylum-calendarman",
					"arkham-asylum-captain-boomerang",
					"arkham-asylum-clayface",
					"arkham-asylum-deathshot",
					"arkham-asylum-firefly",
					"arkham-asylum-gypsy",
					"arkham-asylum-harley-quinn",
					"arkham-asylum-hush",
					"arkham-asylum-james-gordon-junior",
					"arkham-asylum-katana",
					"arkham-asylum-manbat",
					"arkham-asylum-neojoker",
					"arkham-asylum-poison-ivy",
					"arkham-asylum-prometheus",
					"arkham-asylum-riddler",
					"arkham-asylum-scarecrow",
					"arkham-asylum-sofia-falcone",
					"arkham-asylum-solomon-grundy",
					"arkham-asylum-vixen",
					"arkham-asylum-white-knight",
				},

				bat_family = {
					"bat-family-alfred-penyworth",
					"bat-family-azrael",
					"bat-family-batgirl",
					"bat-family-batman-beyond",
					"bat-family-batman-classic",
					"bat-family-batman1000000",
					"bat-family-batwoman",
					"bat-family-blackbat",
					"bat-family-bruce-wayne",
					"bat-family-catwoman",
					"bat-family-huntress",
					"bat-family-james-gordon",
					"bat-family-lucius-fox",
					"bat-family-nightwing",
					"bat-family-oracle",
					"bat-family-red-hood",
					"bat-family-red-robin",
					"bat-family-robin",
					"bat-family-selina-kyle",
				},

				crime_syndicate = {
					"crime-syndicate-black-siren",
					"crime-syndicate-deadeye",
					"crime-syndicate-deathstorm",
					"crime-syndicate-dr-chaos",
					"crime-syndicate-grid",
					"crime-syndicate-johnny-quick",
					"crime-syndicate-martian",
					"crime-syndicate-owlman",
					"crime-syndicate-power-ring",
					"crime-syndicate-sea-king",
					"crime-syndicate-superwoman",
					"crime-syndicate-ultraman",
				},

				emotional_entities = {
					"emotional-entities-adara",
					"emotional-entities-butcher",
					"emotional-entities-entity",
					"emotional-entities-ion",
					"emotional-entities-nekron",
					"emotional-entities-ophidian",
					"emotional-entities-parallax",
					"emotional-entities-predator",
					"emotional-entities-proselyte",
					"emotional-entities-relic",
					"emotional-entities-umbrax",
				},

				injustice_league = {
					"injustice-league-bizarro",
					"injustice-league-black-adam",
					"injustice-league-black-manta",
					"injustice-league-brainiac",
					"injustice-league-captain-cold",
					"injustice-league-cheetah",
					"injustice-league-deathstroke",
					"injustice-league-giganta",
					"injustice-league-gorilla-grod",
					"injustice-league-joker",
					"injustice-league-killer-frost",
					"injustice-league-killercroc",
					"injustice-league-lex-luthor",
					"injustice-league-mr-freeze",
					"injustice-league-mr-terrible",
					"injustice-league-multiman",
					"injustice-league-nocturna",
					"injustice-league-penguin",
					"injustice-league-sinestro",
					"injustice-league-twoface",
				},

				justice_league = {
					"justice-league-adam-strange",
					"justice-league-aquaman",
					"justice-league-batman",
					"justice-league-black-canary",
					"justice-league-blue-beetle",
					"justice-league-booster-gold",
					"justice-league-captain-atom",
					"justice-league-constantine",
					"justice-league-cyborg",
					"justice-league-dr-fate",
					"justice-league-etrigan",
					"justice-league-firestorm",
					"justice-league-flash",
					"justice-league-green-arrow",
					"justice-league-green-lantern-guy-gardner",
					"justice-league-green-lantern-hal-jordan",
					"justice-league-green-lantern-jessica-cruz",
					"justice-league-green-lantern-john-stewart",
					"justice-league-green-lantern-kyle-rayner",
					"justice-league-hawkgirl",
					"justice-league-hawkman",
					"justice-league-lobo",
					"justice-league-martian-manhunter",
					"justice-league-mera",
					"justice-league-mr-terrific",
					"justice-league-raven",
					"justice-league-red-tornado",
					"justice-league-shazam",
					"justice-league-spectre",
					"justice-league-starfire",
					"justice-league-superman",
					"justice-league-wonder-woman",
					"justice-league-zatanna",
				},

				lanter_corps = {
					"lantern-corps-black",
					"lantern-corps-blue",
					"lantern-corps-gold",
					"lantern-corps-green",
					"lantern-corps-indigo",
					"lantern-corps-orange",
					"lantern-corps-phantom-balanced",
					"lantern-corps-phantom-chaos",
					"lantern-corps-phantom-corrupted",
					"lantern-corps-red",
					"lantern-corps-ultraviolet-spectral",
					"lantern-corps-ultraviolet-veiled",
					"lantern-corps-violet",
					"lantern-corps-white",
					"lantern-corps-yellow",
				},

				league_of_assassins = {
					"league-of-assassins-athanasia",
					"league-of-assassins-bane",
					"league-of-assassins-black-spider",
					"league-of-assassins-blank",
					"league-of-assassins-lady-shiva",
					"league-of-assassins-nyssa-raatko",
					"league-of-assassins-ras-al-ghul",
					"league-of-assassins-talia",
				},

				new_gods = {
					apokolips = {
						"apokolips-darkseid",
						"apokolips-desaad",
						"apokolips-grayven",
						"apokolips-heggra",
						"apokolips-kalibak",
						"apokolips-pythia",
						"apokolips-yugakhan",
					},
					new_genesis = {
						"new-genesis-big-barda",
						"new-genesis-highfather",
						"new-genesis-lightray",
						"new-genesis-metron",
						"new-genesis-mister-miracle",
						"new-genesis-orion",
						"new-genesis-takion",
					},
				},

				super_family = {
					"super-family-clark-kent",
					"super-family-composite-superman",
					"super-family-conner-kent",
					"super-family-dreamer",
					"super-family-eradicator",
					"super-family-jonathan-kent",
					"super-family-lois-lane",
					"super-family-lucy-lane",
					"super-family-martha-kent",
					"super-family-steel",
					"super-family-supergirl",
					"super-family-superman-classic",
					"super-family-superman-kingdomcome",
					"super-family-superman-modern",
				},

				watchmen = {
					"watchmen-dr-manhattan",
					"watchmen-nite-owl",
					"watchmen-ozymandias",
					"watchmen-rorschach",
					"watchmen-silk-spectre",
					"watchmen-the-comedian",
				},
			},

			detox = {
				"detox-1998term",
				"detox-ash",
				"detox-bone",
				"detox-bunker",
				"detox-clay",
				"detox-coal",
				"detox-concrete",
				"detox-copper",
				"detox-dust",
				"detox-ember",
				"detox-fog",
				"detox-frost",
				"detox-glass",
				"detox-ink",
				"detox-iron",
				"detox-jade",
				"detox-linen",
				"detox-mercury",
				"detox-moss",
				"detox-moth",
				"detox-mute",
				"detox-paper",
				"detox-petal",
				"detox-plaster",
				"detox-prison",
				"detox-rain",
				"detox-rust",
				"detox-scar",
				"detox-sepia",
				"detox-shadow",
				"detox-silk",
				"detox-silt",
				"detox-slate",
				"detox-smoke",
				"detox-sterile",
				"detox-stone",
				"detox-void",
				"detox-wool",
				"detox-zenkanagawa",
				"detox-zenpaper",
			},

			kanagawa = {
				"kanagawa-paper-crimsonnight",
				-- "kanagawa-paper-dawn",
				"kanagawa-paper-dragon",
				"kanagawa-paper-eclipse",
				"kanagawa-paper-edo",
				"kanagawa-paper-nightfall",
				"kanagawa-paper-obsidian",
				"kanagawa-paper-storm",
				"kanagawa-paper-sunset",
			},

			punk = {
				"acidpunk",
				"aquapunk",
				"atompunk",
				"biopunk",
				"clockpunk",
				"cryopunk",
				"cyberpunk",
				"decopunk",
				"dieselpunk",
				"duskpunk",
				"gothicpunk",
				"junglepunk",
				"junkpunk",
				"nanopunk",
				"solarpunk",
				"splatterpunk",
				"steampunk",
				"stonepunk",
				"techpunk",
			},

			nvim_builtins = {
				"prism-habamax",
				"prism-quiet",
				"prism-retrobox",
				"prism-slate",
				"prism-sorbet",
			},

			tmnt = {
				"tmnt-april-oneal",
				"tmnt-casey-jones",
				"tmnt-donatello",
				"tmnt-last-ronin",
				"tmnt-leonardo",
				"tmnt-michelangelo",
				"tmnt-raphael",
				"tmnt-shredder",
				"tmnt-splinter",
			},
		},

		filetype_themes = {
			alpha = "kanagawa-paper-edo",
			netrw = "kanagawa-paper-edo",
			minifiles = "kanagawa-paper-edo",
			lazy = "kanagawa-paper-edo",
			help = "kanagawa-paper-edo",
			lua = "kanagawa-paper-edo",
			mason = "kanagawa-paper-edo",
			tmux = "kanagawa-paper-edo",
			oil = "kanagawa-paper-edo",
			kdl = "kanagawa-paper-edo",
			toml = "kanagawa-paper-edo",
			conf = "kanagawa-paper-edo",
			sh = "kanagawa-paper-edo",
			zsh = "kanagawa-paper-edo",
			hyprlang = "kanagawa-paper-edo",
			csv = "kanagawa-paper-edo",
			md = "base16-catppuccin-frappe",
			tex = "base16-catppuccin-mocha",
			-- cs = "gruvbox",
			cs = "base16-gruvbox-dark-hard",
			csx = "base16-gruvbox-dark-hard",
			csproj = "base16-gruvbox-dark-pale",
			xml = "base16-gruvbox-dark-pale",
			solution = "base16-gruvbox-material-dark-hard",
			python = "kanagawa-paper-sunset",
			solidity = "base16-darkmoss",
			sql = "kanagawa-paper-dragon",
			sqls = "kanagawa-paper-dragon",
			html = "tokyonight",
			css = "tokyonight",
			javascript = "nordfox",
			typescript = "duskfox",
			json = "base16-rose-pine",
			jsonc = "base16-rose-pine",
		},

		project_themes = {},
	},
}
