name: Simple Neovim CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

jobs:
    check:
        name: Lint, Format & Validate
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Lua
              uses: leafo/gh-actions-lua@v10
              with:
                  luaVersion: "5.1"

            - name: Install LuaRocks
              uses: leafo/gh-actions-luarocks@v4

            - name: Install StyLua
              run: |
                  cargo install stylua
                  stylua --version

            - name: Check Lua Formatting
              run: |
                  if ! stylua --check lua/ init.lua; then
                    echo "::error::StyLua found formatting issues. Run 'stylua lua/ init.lua' locally to fix."
                    exit 1
                  else
                    echo "StyLua: OK"
                  fi

            - name: Install Luacheck
              run: luarocks install luacheck

            - name: Run Luacheck
              run: |
                  if ! luacheck lua/ init.lua --globals vim --no-color --formatter plain; then
                    echo "::error::Luacheck found lint warnings/errors. Inspect the output above."
                    exit 1
                  else
                    echo "Luacheck: OK"
                  fi

            - name: Install Neovim (Stable)
              uses: rhysd/action-setup-vim@v1
              with:
                  neovim: true
                  version: stable

            - name: Validate init.lua Syntax
              env:
                  LUA_PATH: ./lua/?.lua;./lua/?/init.lua;;
                  LUA_CPATH: ./lua/?.so;;
              run: |
                  cd $GITHUB_WORKSPACE
                  nvim --headless -u init.lua -c "lua vim.print('init.lua loaded successfully')" -c "quit" 2>&1 | tee init_output.log
                  if grep -q "Error" init_output.log; then
                    echo "::error::Errors found in init.lua"
                    cat init_output.log
                    exit 1
                  else
                    echo "init.lua: OK"
                  fi

            - name: Install Plugins (Headless)
              env:
                  LUA_PATH: ./lua/?.lua;./lua/?/init.lua;;
                  LUA_CPATH: ./lua/?.so;;
              run: |
                  cd $GITHUB_WORKSPACE
                  nvim --headless "+Lazy! sync" +qa
              timeout-minutes: 5

            - name: Run Health Check
              env:
                  LUA_PATH: ./lua/?.lua;./lua/?/init.lua;;
                  LUA_CPATH: ./lua/?.so;;
              run: |
                  cd $GITHUB_WORKSPACE
                  nvim --headless -c 'redir! > healthcheck.log | silent checkhealth | redir END | qa'
                  if [ -f healthcheck.log ]; then
                    cat healthcheck.log
                  else
                    echo "::error::healthcheck.log not found"
                    exit 1
                  fi

            - name: Run cspell
              uses: streetsidesoftware/cspell-action@v6
              with:
                  config: ./cspell.json
                  incremental_files_only: false
                  check_dot_files: true
                  files: |
                      **/*.lua
                      **/*.md
                      **/*.json
