name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim: [stable, nightly]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Lua + luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Run luacheck (robust)
        run: |
          if [ -d "lua" ]; then
            luacheck lua
          else
            echo "No lua/ directory found, skipping lint."
          fi

      - name: Install Neovim (${{ matrix.neovim }})
        run: |
          if [ "${{ matrix.neovim }}" = "stable" ]; then
            url="https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
          else
            url="https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz"
          fi
          wget "$url"
          tar xzvf nvim-linux64.tar.gz
          echo "$PWD/nvim-linux64/bin" >> $GITHUB_PATH
          export PATH="$PWD/nvim-linux64/bin:$PATH"

      - name: Cache lazy.nvim plugins
        uses: actions/cache@v4
        with:
          path: ~/.local/share/nvim/lazy
          key: ${{ runner.os }}-${{ matrix.neovim }}-lazy-${{ hashFiles('**/lua/**/*.lua') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.neovim }}-lazy-

      - name: Install plugins (Lazy)
        run: nvim --headless "+Lazy! sync" +qa

      - name: Verify Neovim startup
        run: nvim --headless -c 'quitall'

      - name: Run healthcheck
        run: |
          nvim --headless -c 'checkhealth' -c 'quitall'
